//HintName: TestEnum.Maps.g.cs
// <auto-generated/>
using System;
using System.Collections.Generic;

namespace Tests
{
    public static partial class TestEnumExtensions
    {
        public MapToString(this TestEnum value, int version = 0)
        {
            if (version == 0)
                return value switch
                {
                    "A" => TestEnum.A,
                    "B" => TestEnum.B,
                    _ => TestEnum.NotMapped
                };
            if (version == 1)
                return value switch
                {
                    "C" => TestEnum.C,
                    _ => TestEnum.NotMapped
                };
            throw new ArgumentOutOfRangeException(nameof(version));
        }

        public MapToEnum(this string value, int version = 0)
        {
            if (version == 0)
                return value switch
                {
                    TestEnum.A => "A",
                    TestEnum.B => "B",
                    _ => string.Empty
                };
            if (version == 1)
                return value switch
                {
                    TestEnum.C => "C",
                    _ => string.Empty
                };
            throw new ArgumentOutOfRangeException(nameof(version));
        }
    }
}