//HintName: MyClass.FixedWidth.g.cs
// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Tests;
partial class MyClass
{
    public static Dictionary<string, FixedWidthLibraryCore.FixedWidthAttribute> FixedWidthAttributes = new Dictionary<string, FixedWidthLibraryCore.FixedWidthAttribute>
    {
        {
            "FirstName",
            new FixedWidthLibraryCore.FixedWidthString(0, 30)
            {
            }
        }
    };
    public const int TotalFixedWidthLength = 30;
    public MyClass(ReadOnlySpan<char> line)
    {
        FirstName = FixedWidthAttributes["FirstName"].Parse(line);
    }

    public MyClass()
    {
    }

    public StringBuilder WriteToStringBuilder(StringBuilder? stringBuilder = null)
    {
        stringBuilder ??= new StringBuilder();
        FixedWidthAttributes["FirstName"].WriteToStringBuilder(FirstName, stringBuilder);
        stringBuilder.AppendLine();
        return stringBuilder;
    }

    public Stream WriteToStream(Stream stream)
    {
        using var streamWriter = new StreamWriter(stream, leaveOpen: true);
        FixedWidthAttributes["FirstName"].WriteToStream(FirstName, streamWriter);
        return stream;
    }

    public async Task<Stream> WriteToStreamAsync(Stream stream)
    {
        using var streamWriter = new StreamWriter(stream, leaveOpen: true);
        await FixedWidthAttributes["FirstName"].WriteToStreamAsync(FirstName, streamWriter);
        return stream;
    }
}