//HintName: MyClass.FixedWidth.g.cs
// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Tests;
partial class MyClass
{
    public static Dictionary<string, FixedWidthLibraryCore.FixedWidthAttribute> FixedWidthAttributes = new Dictionary<string, FixedWidthLibraryCore.FixedWidthAttribute>
    {
        {
            "FirstName",
            new FixedWidthLibraryCore.FixedWidthAttribute(0, 30)
            {
            }
        }
    };
    public const int TotalFixedWidthLength = 30;
    public MyClass(ReadOnlySpan<char> line)
    {
        FirstName = FixedWidthAttributes["FirstName"].AssignNullable(FirstName, line);
    }

    public MyClass()
    {
    }

    public StringBuilder WriteToStringBuilder(StringBuilder? stringBuilder = null)
    {
        stringBuilder ??= new StringBuilder();
        FixedWidthAttributes["FirstName"].WriteToStringBuilder(FirstName, stringBuilder);
        stringBuilder.AppendLine();
        return stringBuilder;
    }

    public StreamWriter WriteToStream<T>(StreamWriter streamWriter)
    {
        FixedWidthAttributes["FirstName"].WriteToStream(FirstName, streamWriter);
        return streamWriter;
    }

    public async Task<StreamWriter> WriteToStreamAsync<T>(T value, StreamWriter streamWriter)
    {
        await FixedWidthAttributes["FirstName"].WriteToStreamAsync(FirstName, streamWriter);
        return streamWriter;
    }
}