//HintName: MyClass.FixedWidth.g.cs
// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using FixedWidthLibraryCore.FixedWidth;

namespace Tests;
public partial class MyClass
{
    public static class FixedWidthMetaData
    {
        public static readonly FixedWidthLibraryCore.FixedWidth.FixedWidthString FirstName = new FixedWidthLibraryCore.FixedWidth.FixedWidthString(0, 30)
        {
        };
    }

    public const int TotalFixedWidthLength = 30;
    public MyClass(ReadOnlySpan<char> line)
    {
        FirstName = FixedWidthMetaData.FirstName.Parse(line);
    }

    public StringBuilder WriteToStringBuilder(StringBuilder? stringBuilder = null)
    {
        stringBuilder ??= new StringBuilder();
        FixedWidthMetaData.FirstName.WriteToStringBuilder(FirstName, stringBuilder);
        stringBuilder.AppendLine();
        return stringBuilder;
    }

    public Stream WriteToStream(Stream stream)
    {
        using var streamWriter = new StreamWriter(stream, leaveOpen: true);
        FixedWidthMetaData.FirstName.WriteToStream(FirstName, streamWriter);
        return stream;
    }

    public async Task<Stream> WriteToStreamAsync(Stream stream)
    {
        using var streamWriter = new StreamWriter(stream, leaveOpen: true);
        await FixedWidthMetaData.FirstName.WriteToStreamAsync(FirstName, streamWriter);
        return stream;
    }
}