//HintName: TestClassFull.FixedWidth.g.cs
// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using FixedWidthLibraryCore.FixedWidth;

namespace Tests;
public partial class TestClassFull
{
    public static class FixedWidthMetaData
    {
        public static readonly Tests.CustomMap LastName = new Tests.CustomMap(31, 30)
        {
            PadCharacter = '_',
            IndexOffset = 1,
            MapType = typeof(Tests.CustomMap)
        };
    }

    public const int TotalFixedWidthLength = 30;
    public TestClassFull(ReadOnlySpan<char> line)
    {
        LastName = FixedWidthMetaData.LastName.Parse(line);
    }

    public StringBuilder WriteToStringBuilder(StringBuilder? stringBuilder = null)
    {
        stringBuilder ??= new StringBuilder();
        FixedWidthMetaData.LastName.WriteToStringBuilder(LastName, stringBuilder);
        stringBuilder.AppendLine();
        return stringBuilder;
    }

    public Stream WriteToStream(Stream stream)
    {
        using var streamWriter = new StreamWriter(stream, leaveOpen: true);
        FixedWidthMetaData.LastName.WriteToStream(LastName, streamWriter);
        return stream;
    }

    public async Task<Stream> WriteToStreamAsync(Stream stream)
    {
        using var streamWriter = new StreamWriter(stream, leaveOpen: true);
        await FixedWidthMetaData.LastName.WriteToStreamAsync(LastName, streamWriter);
        return stream;
    }
}