//HintName: TestClassFull.FixedWidth.g.cs
// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Tests;
partial class TestClassFull
{
    public static Dictionary<string, FixedWidthLibraryCore.FixedWidthAttribute> FixedWidthAttributes = new Dictionary<string, FixedWidthLibraryCore.FixedWidthAttribute>
    {
        {
            "FirstName",
            new FixedWidthLibraryCore.FixedWidthString(1, 30)
            {
                Format = "yyyyMMdd",
                PadCharacter = '*',
                Pad = FixedWidthLibraryCore.Direction.Left,
                Trim = true,
                AutoTrim = false,
                DateTimeStyles = null,
                AutoTrimDirection = FixedWidthLibraryCore.Direction.Left,
                FalseValue = "ad",
                TrueValue = "DSF",
                IndexOffset = 1,
                NumberStyles = null,
                RemoveChars = "abcd",
                WhiteSpaceToNull = true
            }
        },
        {
            "LastName",
            new FixedWidthLibraryCore.FixedWidthStringNullable(31, 30)
            {
                PadCharacter = '_',
                IndexOffset = 1
            }
        },
        {
            "Age",
            new FixedWidthLibraryCore.FixedWidthInt(61, 3)
            {
                PadCharacter = '*',
                IndexOffset = 1
            }
        },
        {
            "DateOfBirth",
            new FixedWidthLibraryCore.FixedWidthDateTime(64, 8)
            {
                PadCharacter = '_',
                IndexOffset = 1,
                Format = "yyyyMMdd"
            }
        },
        {
            "IsCool",
            new FixedWidthLibraryCore.FixedWidthBool(72, 1)
            {
                PadCharacter = '*',
                IndexOffset = 1,
                TrueValue = "Y",
                FalseValue = "N"
            }
        },
        {
            "Gender",
            new FixedWidthLibraryCore.FixedWidthChar(73, 1)
            {
                PadCharacter = '_',
                IndexOffset = 1
            }
        },
        {
            "Money",
            new FixedWidthLibraryCore.FixedWidthDecimal(74, 100)
            {
                PadCharacter = '*',
                IndexOffset = 1
            }
        },
        {
            "Debt",
            new FixedWidthLibraryCore.FixedWidthDouble(174, 10)
            {
                PadCharacter = '_',
                IndexOffset = 1
            }
        },
        {
            "Wisdom",
            new FixedWidthLibraryCore.FixedWidthFloat(184, 10)
            {
                PadCharacter = '*',
                IndexOffset = 1
            }
        },
        {
            "Height",
            new FixedWidthLibraryCore.FixedWidthLong(194, 100)
            {
                PadCharacter = '_',
                Pad = FixedWidthLibraryCore.Direction.Right,
                IndexOffset = 1
            }
        },
        {
            "D",
            new FixedWidthLibraryCore.FixedWidthDateOnly(194, 100)
            {
                PadCharacter = '_',
                Pad = FixedWidthLibraryCore.Direction.Right,
                IndexOffset = 1
            }
        }
    };
    public const int TotalFixedWidthLength = 393;
    public TestClassFull(ReadOnlySpan<char> line)
    {
        FirstName = FixedWidthAttributes["FirstName"].Parse(line);
        LastName = FixedWidthAttributes["LastName"].Parse(line);
        Age = FixedWidthAttributes["Age"].Parse(line);
        DateOfBirth = FixedWidthAttributes["DateOfBirth"].Parse(line);
        IsCool = FixedWidthAttributes["IsCool"].Parse(line);
        Gender = FixedWidthAttributes["Gender"].Parse(line);
        Money = FixedWidthAttributes["Money"].Parse(line);
        Debt = FixedWidthAttributes["Debt"].Parse(line);
        Wisdom = FixedWidthAttributes["Wisdom"].Parse(line);
        Height = FixedWidthAttributes["Height"].Parse(line);
        D = FixedWidthAttributes["D"].Parse(line);
    }

    public TestClassFull()
    {
    }

    public StringBuilder WriteToStringBuilder(StringBuilder? stringBuilder = null)
    {
        stringBuilder ??= new StringBuilder();
        FixedWidthAttributes["FirstName"].WriteToStringBuilder(FirstName, stringBuilder);
        FixedWidthAttributes["LastName"].WriteToStringBuilder(LastName, stringBuilder);
        FixedWidthAttributes["Age"].WriteToStringBuilder(Age, stringBuilder);
        FixedWidthAttributes["DateOfBirth"].WriteToStringBuilder(DateOfBirth, stringBuilder);
        FixedWidthAttributes["IsCool"].WriteToStringBuilder(IsCool, stringBuilder);
        FixedWidthAttributes["Gender"].WriteToStringBuilder(Gender, stringBuilder);
        FixedWidthAttributes["Money"].WriteToStringBuilder(Money, stringBuilder);
        FixedWidthAttributes["Debt"].WriteToStringBuilder(Debt, stringBuilder);
        FixedWidthAttributes["Wisdom"].WriteToStringBuilder(Wisdom, stringBuilder);
        FixedWidthAttributes["Height"].WriteToStringBuilder(Height, stringBuilder);
        FixedWidthAttributes["D"].WriteToStringBuilder(D, stringBuilder);
        stringBuilder.AppendLine();
        return stringBuilder;
    }

    public Stream WriteToStream(Stream stream)
    {
        using var streamWriter = new StreamWriter(stream, leaveOpen: true);
        FixedWidthAttributes["FirstName"].WriteToStream(FirstName, streamWriter);
        FixedWidthAttributes["LastName"].WriteToStream(LastName, streamWriter);
        FixedWidthAttributes["Age"].WriteToStream(Age, streamWriter);
        FixedWidthAttributes["DateOfBirth"].WriteToStream(DateOfBirth, streamWriter);
        FixedWidthAttributes["IsCool"].WriteToStream(IsCool, streamWriter);
        FixedWidthAttributes["Gender"].WriteToStream(Gender, streamWriter);
        FixedWidthAttributes["Money"].WriteToStream(Money, streamWriter);
        FixedWidthAttributes["Debt"].WriteToStream(Debt, streamWriter);
        FixedWidthAttributes["Wisdom"].WriteToStream(Wisdom, streamWriter);
        FixedWidthAttributes["Height"].WriteToStream(Height, streamWriter);
        FixedWidthAttributes["D"].WriteToStream(D, streamWriter);
        return stream;
    }

    public async Task<Stream> WriteToStreamAsync(Stream stream)
    {
        using var streamWriter = new StreamWriter(stream, leaveOpen: true);
        await FixedWidthAttributes["FirstName"].WriteToStreamAsync(FirstName, streamWriter);
        await FixedWidthAttributes["LastName"].WriteToStreamAsync(LastName, streamWriter);
        await FixedWidthAttributes["Age"].WriteToStreamAsync(Age, streamWriter);
        await FixedWidthAttributes["DateOfBirth"].WriteToStreamAsync(DateOfBirth, streamWriter);
        await FixedWidthAttributes["IsCool"].WriteToStreamAsync(IsCool, streamWriter);
        await FixedWidthAttributes["Gender"].WriteToStreamAsync(Gender, streamWriter);
        await FixedWidthAttributes["Money"].WriteToStreamAsync(Money, streamWriter);
        await FixedWidthAttributes["Debt"].WriteToStreamAsync(Debt, streamWriter);
        await FixedWidthAttributes["Wisdom"].WriteToStreamAsync(Wisdom, streamWriter);
        await FixedWidthAttributes["Height"].WriteToStreamAsync(Height, streamWriter);
        await FixedWidthAttributes["D"].WriteToStreamAsync(D, streamWriter);
        return stream;
    }
}